### ISSUE TITLE
[Request] [Reaper] Plentiful Harvest into Perfectio

### ISSUE THREAD

**Issue by Nillinn** [MKhayle/XIVComboExpanded#352] opened 2024-07-21 23:18 UTC
Feature: Plentiful Harvest turns into Perfectio, when the Perfectio Occulta buff is available.

It just makes sense. Since one can never have both skills available to use at the same time. 
And one MUST use Plentiful Harvest to make Perfectio available. So I might even say these skills are a "combo".

**Comment by MKhayle** [comment] 2024-07-22 00:34
I'll look into it when I'll have time, since I'm currently busy with the plugin's rework.
Reaper already has a ton of features though, so uhhhh we'll see

**Comment by kaedys** [comment] 2024-07-22 15:18
Shouldn't be too hard to add, and it does make a lot of sense.  I'll add it to the existing branch I have for the other two open Reaper feature requests.

**Comment by lhn1703** [comment] 2024-07-22 17:15
> I'll look into it when I'll have time, since I'm currently busy with the plugin's rework. Reaper already has a ton of features though, so uhhhh we'll see

I agree that reaper has too many combos. I can consolidate/combine similar combos and clean up/remove redundant features after the branch rework.

**Comment by kaedys** [comment] 2024-07-22 17:31
The problem is, all of them have distinct purpose.  Like, we have separate features for putting Gibbet or Gallows on each of Soul Slice, the Slice combo, and Shadow of Death.  That's 6 combos for that alone, and none of those can really be consolidated, because they all serve distinct purpose (though imo, putting either one on Shadow of Death is silly, because that's the only one of the 3 that _can_ be used during Enshroud, and _is_ used (twice, in fact) during Enshroud in the double Enshroud burst sequence).

Now, many of the Reaper combos are going to be moved into Secret or Accessibility, which will help with that, but there really aren't _many_ that can just straight up be removed or merged.  The only ones I'd personally see removed would be the ones putting Enshroud stuff on Shadow of Death, because those are just traps, imo, but I suspect some users are using those and wouldn't appreciate their removal.

That said, one thing that definitely _could_ help with the volume of Reaper features, and many other jobs, is to consolidate single target and AoE replacements that are equivalent.  For example, the probability that someone will want the Slice combo to be all-in-oned, but NOT the AoE Scythe combo to be, is basically zilch.  Same for someone wanting Gibbet or Gallows on Slice but not Guillotine on Scythe.  That cuts out nearly half of the combos, imo.

**Comment by lhn1703** [comment] 2024-07-23 01:03
I was thinking more along the lines of:
- deleting shadow of death combos (for obv reasons)
- slice -> gallows + soul slice -> gibbet when reaving/shroud
- slice -> gibbet + soul slice -> gallows when reaving/shroud
- - since g/g is mandatory during reaving/shroud these buttons are practically mutually exclusive with g/g; also who would use slice -> gallows but use gibbet on its own lol
- 1 button shroud (consolidate auto gallows/gibbet with sacrificium/lemure)
- etc.

**Comment by kaedys** [comment] 2024-07-23 04:06
Ya, I could see that.  I was also contemplating playing with a new "secret combo" options where Blood Stalk and Grim Swathe had their natural GCD followup (ie. Gibbet/Gallows/Guillotine, with the first two auto-selected based on buff) included after use, as an alternative to putting them on Slice and Soul Slice.

But I also definitely think we should merge the ST and AoE combos.  Probably also do the same for Viper, tbh.  Picto already has them merged, they were written that way since the first combos were added.  I see very very little reason to have separate combo selections for ST vs. AoE for 1:1 abilities (like the Spinning Scythe combo).

That said, I will contest your argument when it comes to the two pictures immediately above, for one specific reason: Gibbet and Gallows are _positionals_, and which one you start the fight on can definitely matter, while Void Reaping and Cross Reaping are completely interchangeable.  There's no possible loss from the mod deciding to use, save, Void Reaping first versus Cross Reaping, but there definitely _can_ be from the mod deciding to use Gibbet instead of Gallows first, or vice versa.  So there's a distinct reason to use the Enshrouded one but _not_ use the Reaving one, such as, for example, instead using the Slice Gallows and Soul Gibbet features for Reaving, but wanting the all-in-one logic for Enshroud.

But I'm also a _vociferous_ critic of combo features that auto-select between actions with different positional requirements.  IMO _anything_ that combines multiple actions that have _different_ positional requirements onto the same button is automatically an Accessibility class feature, because it will _always_ have significant and notable cases where that's sub-optimal, if for no other reason than not necessarily knowing which one the mod is going to use until it pops up on the button.

**Comment by MKhayle** [comment] 2024-07-23 04:16
> But I'm also a _vociferous_ critic of combo features that auto-select between actions with different positional requirements. IMO _anything_ that combines multiple actions that have _different_ positional requirements onto the same button is automatically an Accessibility class feature, because it will _always_ have significant and notable cases where that's sub-optimal, if for no other reason than not necessarily knowing which one the mod is going to use until it pops up on the button.

100% agreed on that part

**Comment by MKhayle** [comment] 2024-08-09 16:20
2.0.0.0 https://github.com/MKhayle/XIVComboExpanded/commit/16215df0faef50a0a7796e33dfafc9f508d4ab56 is out, and should have fixed this issue. If it doesn't, please re-open this issue!

**Closed by MKhayle** 2024-08-09 16:20 UTC
Labels: dawntrail, should be fixed/done
