### ISSUE TITLE
MNK features doesn't work

### ISSUE THREAD

**Issue by caesarvs** [MKhayle/XIVComboExpanded#312] opened 2024-07-13 00:29 UTC
![Final Fantasy XIV  A Realm Reborn Screenshot 2024 07 12 - 21 24 44 93](https://github.com/user-attachments/assets/43e1435c-b84b-4984-921e-3d650666506c)
![Final Fantasy XIV  A Realm Reborn Screenshot 2024 07 12 - 21 25 04 89](https://github.com/user-attachments/assets/24ccf20a-fbc7-4ef8-858d-07b915514173)
![Final Fantasy XIV  A Realm Reborn Screenshot 2024 07 12 - 21 25 31 85](https://github.com/user-attachments/assets/34ff82d6-bf3f-410a-9f97-51a5e72aaf76)

As per 1.5.12 update, none of the monk combo features marked in the screenshots work.

Other jobs works fine (tested scholar and dancer)

**Comment by MKhayle** [comment] 2024-07-13 01:07
This is because you aren't using the `staging` version of Dalamud and I have introduced features using the new MNK gauge which hasn't been implemented yet in the `release` version of Dalamud. It's featured in the `staging` version, which is akin to a (public) testing version. It's a duplicate of #292.

Your options are the following:
> You can: either type `/xlbranch` in game and pick the `stg`/`staging` branch and restart your game, or patiently wait until Dalamud's `release` has caught up on staging. If you're afraid or anything, you can pick back the `release` branch the exact same way.

**Closed by MKhayle** 2024-07-13 01:07 UTC
Labels: bug, dawntrail

**Comment by caesarvs** [comment] 2024-07-13 01:24
thank you very much!
