### ISSUE TITLE
[Dawntrail] Noticeable FPS loss while combos are happening

### ISSUE THREAD

**Issue by yoshisman8** [MKhayle/XIVComboExpanded#291] opened 2024-07-10 16:33 UTC
I noticed that, for some reason, using any attack or cast a spell while this plugin is active causes a *noticeable* FPS loss during the length of the attack. I assume it is because the combo logic is taxing the system. It's not a deal breaker, but going from 60+ FPS to barely 30 each time i attack is a bit disorienting.

**Comment by MKhayle** [comment] 2024-07-10 16:38
https://github.com/MKhayle/XIVComboExpanded/assets/4359469/1315ef88-9685-4064-83ae-365a7d2ec007

I was using Dragoon with every combo features enabled and didn't notice any FPS loss. I can't reproduce this problem for now. 
Can you provide more info, like the job you're playing and the combos you have active?

**Comment by Efiyo** [comment] 2024-07-10 16:39
I want to say it's not related directly to the combo but maybe Jobbars? https://github.com/0ceal0t/JobBars/issues/226
I've had this exact same issue and I've been restarting the game and testing with every combination until I saw it was probably conflicting with a setting in Jobbars

**Comment by MKhayle** [comment] 2024-07-10 16:41
I am not using jobbars myself, so that's a possibility

**Comment by MKhayle** [comment] 2024-07-10 16:43
Okay, I can confirm this happening. 
Dropped from 80 to 17 fps real quick lmao

**Comment by yoshisman8** [comment] 2024-07-10 16:46
Ok so the issue is from having both Job Bars and XIVCombo enabled at the same time it seems?

**Comment by MKhayle** [comment] 2024-07-10 16:47
More precisely the Icon replacement feature in Job Bars!

**Comment by MKhayle** [comment] 2024-07-10 16:48
I don't know if we can find a way to fix it but I'll probably contact @0ceal0t about this because if it happens with this fork, it will probably also happen with the original XIVCombo and both are main repo plugins

**Comment by yoshisman8** [comment] 2024-07-10 16:54
Either way, disabling only the Icon Replacement feature works flawlessly. Until then i'll just have it off! Thanks for narrowing down the bug!

**Comment by Rubyurek** [comment] 2024-07-10 17:29
i have the same issue. i deactivate it and the fps loss is gone. so the mod is buggy :x

**Comment by MKhayle** [comment] 2024-07-10 17:53
There are definitely things clashing between those two plugins but I don't think trying to fix it on my end is a good idea since it'll break with any other XIVCombo-based forks too anyway

**Comment by lhn1703** [comment] 2024-07-10 18:21
I might be misunderstanding but is this issue affecting xicombo expanded by itself even if I don't have job bars installed? Are they using the same mechanism to swap the icon combos?

**Comment by Nillinn** [comment] 2024-07-10 18:54
> I might be misunderstanding but is this issue affecting xicombo expanded by itself even if I don't have job bars installed? Are they using the same mechanism to swap the icon combos? Is the workaround just installing job bars and disabling the icon replacement feature?

![image](https://github.com/MKhayle/XIVComboExpanded/assets/94562218/d79b4565-cf83-4afe-9f1d-73ede1377b1e)

Untick this box in Job Bars

**Comment by MKhayle** [comment] 2024-07-10 19:02
> I might be misunderstanding but is this issue affecting xicombo expanded by itself even if I don't have job bars installed? Are they using the same mechanism to swap the icon combos? Is the workaround just installing job bars and disabling the icon replacement feature?

If you don't have job bars, you're fine
the issue only happens when you combine jobbars with icon replacement enabled and xivcombo

**Comment by MKhayle** [comment] 2024-07-10 23:21
https://github.com/0ceal0t/JobBars/issues/226#issuecomment-2221668666
Fixed by @0ceal0t earlier in v1.3.1.1, please update your plugins!

**Closed by MKhayle** 2024-07-10 23:21 UTC
Labels: dawntrail
