### ISSUE TITLE
[MNK] Opo,Raptor and Coeurl feature don't work correctly

### ISSUE THREAD

**Issue by Rubyurek** [MKhayle/XIVComboExpanded#302] opened 2024-07-11 19:08 UTC
Opo feature is activated and it should change the ability "bootshine/leaping opo" to "dragon kick" if no buff is present. However, this is not the case. 

Raptor feature & coeurl feature unfortunately work just as poorly. The abilities are unfortunately not changed.

**Comment by MKhayle** [comment] 2024-07-11 19:14
duplicate of #292, 
you can find a temporary fix here : https://github.com/MKhayle/XIVComboExpanded/issues/292#issuecomment-2221775588

> You can: either type /xlbranch and pick the stg branch, or patiently wait until Dalamud's release has caught up on staging

**Comment by AstaSpirit** [comment] 2024-07-11 20:21
In order to avoid opening another post on the same topic, the 'coeurl feature' is not working on my end, the spell "pouncing coeurl" does not become "Demolish" when I don't have a coeurl's fury stack. I am on the stg branch with version 1.5.0.40 of the plugin, my monk job is level 100, and the features I have enabled are "opo feature", "raptor feature", and "coeurl feature".

**Comment by MKhayle** [comment] 2024-07-11 20:37
Thanks for the report! I couldn't test it myself as I'm not > 90 yet 
https://github.com/MKhayle/XIVComboExpanded/commit/4918264ea298c225da6239463d2b3386e0598d85 fixed here, releasing an update soonish

**Comment by MKhayle** [comment] 2024-07-11 20:44
https://github.com/MKhayle/XIVComboExpanded/commit/7a05b658923bfc43676b7903f5f8c6b1f7dad2cd 1.5.0.41 is here !

**Comment by MKhayle** [comment] 2024-07-11 20:52
@AstaSpirit can you confirm it being fixed? that'd be great

**Comment by AstaSpirit** [comment] 2024-07-11 21:02
I confirm that the issue has been resolved, thank you very much and thank you for your responsiveness !

**Closed** 2024-07-11 21:03 UTC
Labels: duplicate, dawntrail, should be fixed/done
