### ISSUE TITLE
[Bug] Monk Combo Features Not Functioning

### ISSUE THREAD

**Issue by StarchildOlive** [MKhayle/XIVComboExpanded#311] opened 2024-07-12 23:14 UTC
**Describe the bug**
As far as I can tell, no features included for Monk past level 90 function. Currently at level 91.

Attempted with "monke mode", as well as with Opo, Raptor, and Coeurl Feature. ST Balance Feature, Monk AoE Combo, Perfect Balance Feature, Riddle of Brotherly Fire, and Riddle of Fire and Wind also do not function as intended (ie, replacing abilities).

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:

Plugin Version 1.5.1.2

Job Affected - Monk

Currently Enabled:
- Opo Feature
 - Bootshine Steeled Meditation Feature
 - Opomatic Chakra Feature 
- Raptor Feature
- Coeurl Feature 
- ST Balance Feature
- Monk AoE Combo
 - Automatic AoE Chakra Feature
- Perfect Balance Feature
- Riddle of Brotherly Fire
- Riddle of Fire and Wind

Skills placed on Hotbar:
Bootshine, True Strike, Snap Punch, Perfect Balance, Riddle of Fire

As far as I'm aware, I am not using any other fork of XIVCombo. I ensured to uninstall the old one marked "XIV Combo" prior to 7.0.

**Expected behavior**
Abilities should replace themselves as advertised.

**Screenshots or videos**
If applicable, add screenshots/videos to help explain your problem.

Hotbar out of combat (not my usual setup but adjusted for visibility)
![image](https://github.com/user-attachments/assets/3abceece-5c6d-434a-b1bb-59294f86e9ee)

Hotbar after using Riddle of Fire
![image](https://github.com/user-attachments/assets/aaa6508e-cdad-431f-a293-1fe84f0a6a6d)

Hotbar after using Bootshine
![image](https://github.com/user-attachments/assets/ba5e9516-3e4a-41f5-bfd5-4f8aaa9db38d)

Hotbar after using True Strike
![image](https://github.com/user-attachments/assets/4dc7d18a-1bd1-4bc9-843a-6c26beca4305)

Hotbar after using Snap Punch
![image](https://github.com/user-attachments/assets/064317ac-e8d6-4335-b88a-a8f1910e5df1)

**Additional context**
Attempted without other plugins active; no change. Screenshots do not show without plugins, but personal attempts were still done (given that I use a handful, especially some minor gameplay altering ones such as Pandora's Box and Simple Tweaks).

**Comment by MKhayle** [comment] 2024-07-12 23:24
This is because you aren't using the `staging` version of Dalamud and I have introduced features using the new MNK gauge which hasn't been implemented yet in the `release` version of Dalamud. It's featured in the `staging` version, which is akin to a (public) testing version. It's a duplicate of #292.

Your options are the following:
> You can: either type `/xlbranch` in game and pick the `stg`/`staging` branch and restart your game, or patiently wait until Dalamud's `release` has caught up on staging. If you're afraid or anything, you can pick back the `release` branch the exact same way.

**Closed by MKhayle** 2024-07-12 23:24 UTC
Labels: bug, dawntrail
