### ISSUE TITLE
[mnk] update not working

### ISSUE THREAD

**Issue by kaine3d** [MKhayle/XIVComboExpanded#292] opened 2024-07-10 23:34 UTC
looks like the recent monk update isn't actually doing anything. tried updating, restarting, and on other classes which all work, maybe i'm doing something wrong.

**Comment by MKhayle** [comment] 2024-07-10 23:48
![image](https://github.com/MKhayle/XIVComboExpanded/assets/4359469/3a6396ee-ec94-490b-a216-94f9b7cb0a25)
It works flawlessly for me. If you used the previous bindings from Endwalker, you may have to swap them, since I inverted the replaced skills.

**Comment by MKhayle** [comment] 2024-07-10 23:54
although Coeurl Feature has a typo, Demolish & Snap Punch are swapped in the description

**Comment by MKhayle** [comment] 2024-07-10 23:57
(typo fixed in 1.5.0.31)

**Comment by Liracy** [comment] 2024-07-11 00:03
Having the exact same issues. Monk isn't replacing the appropriate abilities. Bootshine not replacing with anything I have selected. Have monke mode on and Opo Raptor and Coeurl off. Any ideas? Would be happy to test with you in real time as you seem active on this thread.

**Comment by MKhayle** [comment] 2024-07-11 00:10
What is your level ? I may have forgotten to take into account the lvl 92 upgrade of those skills

**Comment by Liracy** [comment] 2024-07-11 00:10
My monk is level 60!

**Comment by kaine3d** [comment] 2024-07-11 00:13
78 here will poke at it some more

**Comment by MKhayle** [comment] 2024-07-11 00:14
Are you up to date to the latest version (1.5.0.31?)

**Comment by MKhayle** [comment] 2024-07-11 00:16
I went into a lvl 60 dungeon, synchronized, and died to a pack of mobs after succesfully using those combos
monke mode only uses bootshine and the AoE combo only uses masterful blitz

**Comment by Liracy** [comment] 2024-07-11 00:16
Wow, I just installed the plugin like 30 minutes ago, but no. I was not updated. Let me try it now!

**Comment by MKhayle** [comment] 2024-07-11 00:20
I am going to try reproducing your issue but so far I don't see why it would happen.

**Comment by MKhayle** [comment] 2024-07-11 00:25
also: monke mode is exclusive and will disable itself if paired with op/coeurl/raptor features

**Comment by Liracy** [comment] 2024-07-11 00:26
I am pretty novice when it comes to monk, but I have those features all off because the addon states that there is a conflict. If I am understanding monke right. I should be placing bootshine on the bar and when I attack it should be advancing through combos. Correct?

**Comment by MKhayle** [comment] 2024-07-11 00:29
Yes, that's how the monke mode is designed
add me on discord: khayle

**Comment by MKhayle** [comment] 2024-07-11 00:43
Alright, that issue was fixed after switching to staging Dalamud ; the current release branch isn't up to date with the new gauge data used for MNK.

**Closed by MKhayle** 2024-07-11 00:43 UTC

**Comment by kaine3d** [comment] 2024-07-11 00:56
that fixed it thanks so much knew it had to be some little stupid but important detail
