### ISSUE TITLE
Astrologian Play to Draw feature; select cards

### ISSUE THREAD

**Issue by bflaxman92** [MKhayle/XIVComboExpanded#443] opened 2024-09-02 23:50 UTC
I use the Play I/2/3 and Minor Arcana to Astral/Umbral Draw feature. Is there any way to allow us to select which of the 4 cards that turn into Draw after being played? I'd personally like for Play 1 and Minor Arcana to become Draw, but not play 2 or play 3.

**Comment by kaedys** [comment] 2024-09-03 15:53
Duplicate of #422, which is planned to be implemented.

**Closed** 2024-11-17 01:24 UTC
Labels: duplicate, dawntrail
