### ISSUE TITLE
[Bug] Issues with Reawaken Combos - Generation/Legacy Abilities

### ISSUE THREAD

**Issue by Zynyx** [MKhayle/XIVComboExpanded#333] opened 2024-07-16 03:30 UTC
**Describe the bug**

Technically this one kind of works, but it is a bit wonky having 3 different options all essentially doing the same thing and 2 of them don't work. 

As the picture below depicts, you have a All-in-One Reawaken feature which works correctly by replacing Reawaken in order with Reawaken > First Generation > First Legacy > Second Generation > Second Legacy > Third Generation > Third Legacy > Fourth Generation > Fourth Legacy > Ouroboros

The other two seem to replace either Steel fangs/Dread Fangs or Steel maw/Dread maw with First Generation > FIrst Legacy; however, once you get past first Legacy it simple cycles through the rest of the generations and skips all the legacies. 

Note: I'm also using the Viper PVP Style Main Combo and the AoE version of that same option for thosr paticular keys on my setup, not sure if it affects this.

Technically; the first option works as advertised. You could simply leave it at that and remove the broken ones if you want. In my personal opinion, the other two are more intuitive. I think it makes the most sense to put it on the Main Combo, but either way the broken ones should either be fixed or removed. 

Sidenote: I also opened a ticket regarding the issues with Pit of Dread/ oGCD issues today which was closed, but the changes aren't in. Does that mean its coming in during the next release or am I just blind?

Thanks again!

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. 1.5.1.5
2. VPR
3. 
![Reawaken](https://github.com/user-attachments/assets/ade41039-6655-4fdd-b35c-fde0755b309e)

4. 5. Are you using any other XIVCombo fork? because you shouldn't --- No

**Comment by kaedys** [comment] 2024-07-16 06:26
The `Generation Legacy Feature` doesn't cycle the rest of the generations or legacies at all.  All those two do is make it so when you use one of the Generation abilities (naturally on Steel Fangs, Dread Fangs, Hunter's Coil, and Swiftskin's Coil, in order, and their AoE equivalents), it then adds the matching Legacy to that same button.  There's no auto-progression of the Generations at all with that feature.

I think what's going weird here is that you have both the PvP combo and the Generation Legacy feature selected.  They should _probably_ be mutually exclusive (or we need to reorganize the code around it, probably the better option).  In any case, you're correct that the PvP combo does not currently include the Legacies, and it probably should.  It actually doesn't look like it includes _any_ of the oGCDs, but we should probably go ahead an integrate all of the various oGCD features in it.

As for your dread combo, it was fixed in #331, which has been merged, but not yet released for download.  MKhayle has been working on a refactor and did not have time to run the release on it last night, from what I understand.  Should be out Soon™

**Comment by kaedys** [comment] 2024-07-16 17:25
Ya, I think if the user has selected the options to include the oGCDs on the main combo buttons separate from the PvP combo, we should also honor that in the PvP combo code.  Rather confusing otherwise >.<

That said, if we do that, the job is functionally a two-button job: one for the main combo sequence, including oGCDs and the entire Reawaken sequence (with Legacies), and one for the Dreadwinder features, and the latter _may_ also be included in the main combo button if we also honor the automatic Dreadwinder inclusion feature.  That's probably more automation of the job than we really want to support.  Viper really is quite a simple job already, tbh.  Depends on whether we want a `monke mode` for Viper, basically.

**Comment by masanbol** [comment] 2024-07-16 17:40
I'll defer to @MKhayle on this, but my feeling is that combining the Legacies or other oGCDs onto the PvP all-in-one buttons would take this beyond even monke mode - you could conceivably play Viper close to optimal with 3 buttons. IMO, we should clean up and make mutually exclusive the parts of this that interfere with one another, and maybe include some text that lets players know that the PvP combos are intended to be separate from the oGCDs, so if you use them you'll also need to activate the Twinfang/Twinblood->Serpent's Tail feature and/or the Reawaken all-in-one to play it as intended.

**Comment by MKhayle** [comment] 2024-07-16 17:58
I think we can discuss this once #323 would be done with, with better attribute options to classify things in a more satisfying way

**Comment by MKhayle** [comment] 2024-08-09 16:21
2.0.0.0 https://github.com/MKhayle/XIVComboExpanded/commit/16215df0faef50a0a7796e33dfafc9f508d4ab56 is out, and should have fixed this issue. If it doesn't, please re-open this issue!

**Closed by MKhayle** 2024-08-09 16:21 UTC
Labels: dawntrail, should be fixed/done
