### ISSUE TITLE
[Bug] PLD 125 Royal Authority  > 128 Atonement

### ISSUE THREAD

**Issue by ViciousVictor** [MKhayle/XIVComboExpanded#354] opened 2024-07-22 18:30 UTC
**Describe the bug**
PLD Royal Authority combo (125) > atonement (128) isn't working 

Fast Blade > Riot Blade > Royal Authority > (bug)
the button gets replaced with atonement, but then gets immediately replaced by Fast Blade

on second cycle of 123 with Atonement Ready, this is working correctly
( Atonement Ready ) Fast Blade > Riot Blade > Royal Authority > Atonement

reproduce by clicking off the Atonement Ready buff before the 123

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. Which plugin version you have
v1.5.1.9
2. Which job is affected
PLD
3. What are your enabled combos for that job
125  128  126 132 136 137 140
4. Which skill is placed in your hotbar
Royal Authority
5. Are you using any other XIVCombo fork? because you shouldn't

**Expected behavior**
Fast Blade > Riot Blade > Royal Authority >  ( Atonement Ready ) Atonement 

**Screenshots or videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

maybe the buff check is happening before the buff appears?

https://github.com/user-attachments/assets/b008cefc-b9f3-4ace-b519-0ee774e9f62b

**Comment by MKhayle** [comment] 2024-07-22 19:49
duplicate of #351 
won't fix and not a bug, but planned to update how the plugin works in general

**Comment by MKhayle** [comment] 2024-08-05 09:06
#323 will update this soon

**Comment by MKhayle** [comment] 2024-08-08 12:47
@kaedys reworked PLD entirely, so this will be fixed in 2.0.0.0

**Comment by kaedys** [comment] 2024-08-08 14:13
Specifically, the default Royal Authority -> Atonement feature uses the full 3-part Atonement combo immediately after Royal Authority, which many users find more intuitive.  The Divine Might combo was similarly changed..  There is now a separate sub-combo that adds the optimization-center behavior modification of delaying usage of both Divine Might and Supplication/Sepulchre until they'd be overwritten by a new Royal Authority (as well as improving the optimization logic during Fight or Flight, and a few other tweaks).

**Comment by MKhayle** [comment] 2024-08-09 16:21
2.0.0.0 https://github.com/MKhayle/XIVComboExpanded/commit/16215df0faef50a0a7796e33dfafc9f508d4ab56 is out, and should have fixed this issue. If it doesn't, please re-open this issue!

**Closed by MKhayle** 2024-08-09 16:21 UTC
Labels: dawntrail, planned
